/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param month Month label (yyyy-MM)
 * @param booked 
 * @param completed 
 * @param cancelled 
 */


data class AppointmentsByMonth (

    /* Month label (yyyy-MM) */
    @field:JsonProperty("month")
    val month: kotlin.String,

    @field:JsonProperty("booked")
    val booked: kotlin.Long,

    @field:JsonProperty("completed")
    val completed: kotlin.Long,

    @field:JsonProperty("cancelled")
    val cancelled: kotlin.Long

)

