/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param areaId 
 * @param areaName 
 */


data class AreaInfo (

    @field:JsonProperty("areaId")
    val areaId: kotlin.Long,

    @field:JsonProperty("areaName")
    val areaName: kotlin.String

)

