/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model

import com.clinic.model.AppointmentsByMonth
import com.clinic.model.KpiStats
import com.clinic.model.RevenueByArea
import com.clinic.model.RevenueByMonth

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param kpi 
 * @param revenueByMonth 
 * @param appointmentsByMonth 
 * @param revenueByArea 
 */


data class DashboardStatsResponse (

    @field:JsonProperty("kpi")
    val kpi: KpiStats,

    @field:JsonProperty("revenueByMonth")
    val revenueByMonth: kotlin.collections.List<RevenueByMonth>,

    @field:JsonProperty("appointmentsByMonth")
    val appointmentsByMonth: kotlin.collections.List<AppointmentsByMonth>,

    @field:JsonProperty("revenueByArea")
    val revenueByArea: kotlin.collections.List<RevenueByArea>

)

