/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param revenueMonth Revenue for the current month (€)
 * @param revenuePrevMonth Revenue for the previous month (€)
 * @param activePatients Number of active patients in the period
 * @param newPatients New patients registered in the period
 * @param appointmentsMonth Total appointments in the current month
 * @param cancellationRate Appointment cancellation rate (0–1)
 * @param agendaOccupancy Agenda occupancy rate (0–1)
 */


data class KpiStats (

    /* Revenue for the current month (€) */
    @field:JsonProperty("revenueMonth")
    val revenueMonth: kotlin.Double,

    /* Revenue for the previous month (€) */
    @field:JsonProperty("revenuePrevMonth")
    val revenuePrevMonth: kotlin.Double,

    /* Number of active patients in the period */
    @field:JsonProperty("activePatients")
    val activePatients: kotlin.Long,

    /* New patients registered in the period */
    @field:JsonProperty("newPatients")
    val newPatients: kotlin.Long,

    /* Total appointments in the current month */
    @field:JsonProperty("appointmentsMonth")
    val appointmentsMonth: kotlin.Long,

    /* Appointment cancellation rate (0–1) */
    @field:JsonProperty("cancellationRate")
    val cancellationRate: kotlin.Double,

    /* Agenda occupancy rate (0–1) */
    @field:JsonProperty("agendaOccupancy")
    val agendaOccupancy: kotlin.Double

)

