/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param revenueMonth Total revenue for the current month
 * @param revenuePrevMonth Total revenue for the previous month
 * @param activePatients Number of active patients (booked or confirmed appointments this month)
 * @param newPatients New patients registered this month
 * @param appointmentsMonth Total appointments this month
 * @param cancellationRate Cancellation rate as a percentage
 * @param agendaOccupancy Agenda occupancy rate as a percentage
 */


data class KpiStats (

    /* Total revenue for the current month */
    @field:JsonProperty("revenueMonth")
    val revenueMonth: kotlin.Double,

    /* Total revenue for the previous month */
    @field:JsonProperty("revenuePrevMonth")
    val revenuePrevMonth: kotlin.Double,

    /* Number of active patients (booked or confirmed appointments this month) */
    @field:JsonProperty("activePatients")
    val activePatients: kotlin.Long,

    /* New patients registered this month */
    @field:JsonProperty("newPatients")
    val newPatients: kotlin.Long,

    /* Total appointments this month */
    @field:JsonProperty("appointmentsMonth")
    val appointmentsMonth: kotlin.Long,

    /* Cancellation rate as a percentage */
    @field:JsonProperty("cancellationRate")
    val cancellationRate: kotlin.Double,

    /* Agenda occupancy rate as a percentage */
    @field:JsonProperty("agendaOccupancy")
    val agendaOccupancy: kotlin.Double

)

