/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param month Month label (yyyy-MM)
 * @param total Total revenue for the month (€)
 */


data class RevenueByMonth (

    /* Month label (yyyy-MM) */
    @field:JsonProperty("month")
    val month: kotlin.String,

    /* Total revenue for the month (€) */
    @field:JsonProperty("total")
    val total: kotlin.Double

)

