/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param month Month in yyyy-MM format
 * @param total 
 */


data class RevenueByMonth (

    /* Month in yyyy-MM format */
    @field:JsonProperty("month")
    val month: kotlin.String,

    @field:JsonProperty("total")
    val total: kotlin.Double

)

