/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model

import com.clinic.model.AreaInfo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param area 
 * @param total 
 */


data class RevenueByArea (

    @field:JsonProperty("area")
    val area: AreaInfo,

    @field:JsonProperty("total")
    val total: kotlin.Double

)

