-- V2 H2: Create doctor table
CREATE TABLE doctor (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(100) NOT NULL,
    last_name      VARCHAR(100) NOT NULL,
    specialization VARCHAR(200) NOT NULL,
    email          VARCHAR(255) NOT NULL UNIQUE,
    license_number VARCHAR(50)  NOT NULL UNIQUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_doctor_email   ON doctor(email);
CREATE INDEX idx_doctor_license ON doctor(license_number);
